version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing-system-dashboard-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_BASEURL: ${NEXT_BASEURL}
    env_file:
      - .env
    restart: unless-stopped
