version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-template-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_API_URL: ${NEXT_API_URL}
    env_file:
      - .env
    restart: unless-stopped
